# Generated by Django 5.1 on 2025-11-07 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Webtoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('genero', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('portada', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('En curso', 'En curso'), ('Finalizado', 'Finalizado'), ('Hiato', 'Hiato')], default='En curso', max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webtoons', to='app_Webtoon.usuario')),
            ],
        ),
    ]
